cloudflare:
  # X_AUTH_KEY, check documentation of cloudflare
  x_auth_key: 
  # ZONE ID, on the lower right corner of domain page
  zone_id:
  # Cloudflare Email address
  email:
  # Cloudflare DNS record name
  dns_record_name:
  # Cloudflare DNS record, full url
  website_url:
  # Interval of speedtest on success
  interval: 600
  # Interval of speedtest on error
  retry_interval: 10
  # the raw IP which is the fallback when cloudflare has no speed
  fallback_raw: 
email:
  # notification when switched from fallback to cloudflare
  on_recovery:
    enable: true
    subject: [Success] Best Cloudflare IP has been selected
    body: "Cloudflare IP switched to: %IP%"
  # notification when switched to fallback
  on_fallback:
    enable: true
    subject: [Warning] Fallback IP is being used, use with care
    body: "Fallback IP is being used: %IP%"
  # notification on error happened
  on_error: 
    enable: true
    subject: [Error] Cloudflare Dynamic Best
    body: "Error: %ERROR%"
  # notification when cloudflare lacks speed
  on_cloudflare_no_speed: 
    enable: true
    subject: [Warning] Cloudflare lack speed
    body: "Cloudflare no speed detected"
  # email to notify
  email:
  # smtp username
  smtp_username:
  # smtp password
  smtp_password:
  # smtp server
  smtp_server:
